// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgTools.Data;

#nullable disable

namespace MtgTools.Data.Migrations
{
    [DbContext(typeof(MtgToolsDbContext))]
    partial class MtgToolsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MtgTools.Data.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ArenaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttractionLights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Booster")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardBackId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CardmarketId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cmc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorIndicator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContentWarning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Defense")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Digital")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EdhrecRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Finishes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameEffects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FullArt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GameChanger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Games")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandModifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HighresImage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IllustrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUris")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Legalities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LifeModifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Loyalty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MtgoFoilId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MtgoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MultiverseIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Oversized")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PennyRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintedTypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintsSearchUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProducedMana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Promo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromoTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseUris")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedUris")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reprint")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Reserved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RulingsUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallSetUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Set")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetSearchUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SetUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StorySpotlight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TcgplayerEtchedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TcgplayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Textless")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Toughness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Variation")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VariationOf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Watermark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OracleId");

                    b.HasIndex("SetId");

                    b.HasIndex("Set", "CollectorNumber");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgTools.Data.Models.Ruling", b =>
                {
                    b.Property<Guid>("OracleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.HasKey("OracleId", "Source", "PublishedAt", "Comment");

                    b.HasIndex("OracleId");

                    b.ToTable("Rulings");
                });

            modelBuilder.Entity("MtgTools.Data.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArenaCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("CardCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Digital")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FoilOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconSvgUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MtgoCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NonfoilOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentSetCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrintedSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScryfallUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TcgplayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("MtgTools.Data.Models.Card", b =>
                {
                    b.HasOne("MtgTools.Data.Models.Set", "CardSet")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("MtgTools.Data.Models.CardFace", "CardFaces", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Artist")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("ArtistId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("CardId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Cmc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ColorIndicator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Colors")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Defense")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FlavorText")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("IllustrationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ImageUris")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Layout")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Loyalty")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ManaCost")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<Guid?>("OracleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OracleText")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Power")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PrintedName")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PrintedText")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PrintedTypeLine")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Toughness")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeLine")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Watermark")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("CardId");

                            b1.ToTable("CardFaces", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CardId");
                        });

                    b.OwnsOne("MtgTools.Data.Models.PreviewInfo", "Preview", b1 =>
                        {
                            b1.Property<Guid>("CardId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("PreviewedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("PreviewedAt");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("TEXT")
                                .HasColumnName("PreviewSource");

                            b1.Property<string>("SourceUri")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT")
                                .HasColumnName("PreviewSourceUri");

                            b1.HasKey("CardId");

                            b1.ToTable("Cards");

                            b1.WithOwner()
                                .HasForeignKey("CardId");
                        });

                    b.OwnsMany("MtgTools.Data.Models.RelatedCard", "AllParts", b1 =>
                        {
                            b1.Property<Guid>("CardId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Component")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TypeLine")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Uri")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT");

                            b1.HasKey("CardId", "Id");

                            b1.ToTable("CardAllParts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CardId");
                        });

                    b.Navigation("AllParts");

                    b.Navigation("CardFaces");

                    b.Navigation("CardSet");

                    b.Navigation("Preview")
                        .IsRequired();
                });

            modelBuilder.Entity("MtgTools.Data.Models.Set", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
